[build]
  command = "npm run build"  
  publish = "build"          

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Set headers, for example, to enable CORS
  "/*"
  Access-Control-Allow-Origin = "*"
